/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.clevertec.tasks.olga.utils;

import static org.apache.commons.lang3.StringUtils.isNumeric;

public class Library {
    public boolean isPositiveNumber(String str) {
        if (isNumeric(str)) {
            return Integer.parseInt(str) >= 0;
        }
        return false;
    }
}
