/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.clevertec.tasks.olga.utils;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

public class LibraryTest {

    private Library lib = new Library();

    @Test
    public void isPositive_positive_true() {
        String numeric = "5";

        assertTrue(lib.isPositiveNumber(numeric));
    }

    @Test
    public void isPositive_negative_false() {
        String numeric = "-5";

        assertFalse(lib.isPositiveNumber(numeric));
    }
}
